.github/workflows/node.js.yml
Update node-version
Refs: CU-8695pn6zm
=> chore: Modify workflow

frontend/src/Components/Buttons/Menu/MenuButton.tsx, frontend/src/Components/Navbar/Navbar.tsx, frontend/src/Components/SuggestedUsers/SuggestedUsers.tsx, frontend/src/Components/SuggestedUsers/index.tsx, frontend/src/Pages/Root/Root.tsx, frontend/src/Pages/Search/Search.tsx, frontend/src/Pages/Search/index.tsx, frontend/src/main.tsx
Implement paths,
Repair menu button,
Add some dummy data
Add missing styles for datepicker components
Complete implementation of page
=> Cu 8696pcxy1 create search page patryk kosiski

frontend/src/Components/FriendDetailed/FriendDetailed.tsx, frontend/src/Components/FriendDetailed/index.tsx, frontend/src/Components/Navbar/Navbar.tsx, frontend/src/Pages/Friends/Friends.tsx, frontend/src/Pages/Friends/index.tsx, frontend/src/Pages/Root/Root.tsx
Add new root for friends
Add first version of friends page
Refs: CU-8696pcy8n
=> Cu 8696pcy8n create friends page patryk kosiski

frontend/src/Components/Navbar/Navbar.tsx, frontend/src/Pages/Groups/Groups.tsx, frontend/src/Pages/Groups/index.tsx, frontend/src/Pages/Root/Root.tsx
Add new root for groups
Add first version of groups page
Refs: CU-8696pcyge
=> feature: Add group tab

frontend/src/Components/Navbar/Navbar.tsx, frontend/src/Pages/Following/Following.tsx, frontend/src/Pages/Following/index.tsx, frontend/src/Pages/Root/Root.tsx
Add new root for following
Add basic construction
Refs: CU-8696pcykt
=> feature: Add following tab

backend/src/main/java/meowhub/backend/repositories/CommentRepository.java, backend/src/main/java/meowhub/backend/repositories/PostPictureRepository.java, backend/src/main/java/meowhub/backend/repositories/ProfileDataRepository.java, backend/src/main/java/meowhub/backend/repositories/ProfilePictureRepository.java, backend/src/main/java/meowhub/backend/repositories/ProfileRepository.java, backend/src/main/java/meowhub/backend/repositories/ProfileUserDataRepository.java, backend/src/main/java/meowhub/backend/repositories/RelationTypeRepository.java, backend/src/main/java/meowhub/backend/repositories/UserRelationRepository.java, backend/src/main/java/meowhub/backend/users/repositories/PictureRepository.java, backend/src/test/java/meowhub/backend/InitDataTestConfig.java
=> feature: Create test configuration that inits needed data

frontend/src/Components/CookiesPopup/CookiesPopup.tsx, frontend/src/Components/CookiesPopup/index.tsx, frontend/src/Pages/Root/Root.tsx, frontend/src/main.tsx
Create Cookie notification for application and display it for new users
Refs: CU-8692r5m3u
=> feature: Create cookie notification

frontend/src/Components/Cards/Post/Post.tsx, frontend/src/Components/Cards/Post/index.tsx, frontend/src/Components/ImageWithSkeleton/ImageWithSkeleton.tsx, frontend/src/Pages/MainPage/MainPage.tsx, frontend/src/Services/DTOs/Post.tsx, frontend/src/Services/DTOs/User.tsx
Create base of Post
- Create ImageWithSkeleton for faster replace of images with loading.
- Create DTOs used for data integration with backend.
Refs: CU-86971g2py
=> feature: Create post design

frontend/package-lock.json, frontend/package.json, frontend/src/Providers/AlertProvider.tsx, frontend/src/Services/api.ts, frontend/src/main.tsx
- Update Mantine from 7.14 -> 7.15
- Add Mantine notifications dependency
- Create AlertProvider
- Add interceptor for api to throw notifications when there's an error
Refs: CU-8697352uj
=> feature: Create AlertProvider

frontend/src/Pages/Register/Register.tsx, frontend/src/Services/Constants/Gender.tsx, frontend/src/Services/DTOs/Register.tsx, frontend/src/Translations/en/login.json, frontend/src/Translations/en/register.json, frontend/src/Translations/pl/login.json, frontend/src/Translations/pl/register.json
- Adapt register form with new values
- Correct translations
- Adapt static gender values
Refs: CU-8697369r5
=> feature: Correct register form

frontend/src/Components/Navbar/Navbar.tsx
Make the navbar responsive depending on height
Refs: CU-869739xd3
=> fix: Repair navbar

frontend/src/Features/Search/Search.tsx, frontend/src/Features/Search/components/SearchResults/SearchResults.tsx, frontend/src/Features/Search/components/SearchResults/index.tsx, frontend/src/Features/Search/components/SuggestedUsers/SuggestedUsers.tsx
- Add SearchResults which will react with query parameter,
- Enhance Search mechanizm.
Refs: 8697653ha
=> feature: Enhance Search bar with query parameter

backend/src/main/java/meowhub/backend/posts/controllers/PostController.java, backend/src/main/java/meowhub/backend/posts/services/impl/PostServiceImpl.java, backend/src/main/java/meowhub/backend/security/controllers/AuthController.java, backend/src/main/java/meowhub/backend/security/services/impl/AuthServiceImpl.java, backend/src/main/java/meowhub/backend/security/services/impl/UserDetailsServiceImpl.java, backend/src/main/java/meowhub/backend/shared/constants/AlertConstants.java, backend/src/main/java/meowhub/backend/shared/constants/AlertLevel.java, backend/src/main/java/meowhub/backend/shared/dtos/AlertDto.java, backend/src/main/java/meowhub/backend/shared/exceptions/NotUniqueObjectException.java, backend/src/main/java/meowhub/backend/shared/handlers/GlobalExceptionHandler.java, backend/src/main/java/meowhub/backend/shared/utils/AlertUtils.java, backend/src/main/java/meowhub/backend/users/controllers/UserController.java, backend/src/main/java/meowhub/backend/users/services/impl/UserServiceImpl.java, backend/src/test/java/meowhub/backend/auth/AuthControllerIntegrationTest.java, backend/src/test/java/meowhub/backend/posts/PostControllerIntegrationTest.java, backend/src/test/java/meowhub/backend/shared/GlobalExceptionHandlerTest.java
Developer tests and documentation: 
[[Testy dev] EPIC - API v3 - create AlertDto and global error handling.docx](https://github.com/user-attachments/files/18223222/Testy.dev.EPIC.-.API.v3.-.create.AlertDto.and.global.error.handling.docx)
Link: https://pejot.sharepoint.com/:w:/s/MeowHub/ERF5iCgXBmJLvA5D_0Kz7cIBIp3kvYWeeeYxIeV3DbTviA?e=FaoUHG
Task: 8696zwhj1
Preview of the attached document:
=> feature: Add unified global exception handling using AlertDto

frontend/src/Features/Login/components/ParticleBg/ParticleBg.tsx
- Cache component to prevent refreshing
Refs: 86936x35u
=> bug: Update particles

backend/src/main/java/meowhub/backend/profiles/controllers/ProfileController.java, backend/src/main/java/meowhub/backend/profiles/repositories/ProfilePictureRepository.java, backend/src/main/java/meowhub/backend/profiles/services/ProfileService.java, backend/src/main/java/meowhub/backend/profiles/services/impl/ProfileServiceImpl.java
=> feature: add getUserMedia endpoint

backend/src/main/java/meowhub/backend/posts/controllers/CommentController.java, backend/src/main/java/meowhub/backend/posts/dtos/CommentDto.java, backend/src/main/java/meowhub/backend/posts/models/Comment.java, backend/src/main/java/meowhub/backend/posts/models/Post.java, backend/src/main/java/meowhub/backend/posts/repositories/CommentRepository.java, backend/src/main/java/meowhub/backend/posts/repositories/PostRepository.java, backend/src/main/java/meowhub/backend/posts/services/CommentService.java, backend/src/main/java/meowhub/backend/posts/services/impl/CommentServiceImpl.java, backend/src/main/java/meowhub/backend/posts/services/impl/PostServiceImpl.java, backend/src/test/java/meowhub/backend/posts/PostRepositoryIntegrationTest.java, backend/src/test/java/meowhub/backend/posts/PostServiceImplTest.java, database/scripts/120_create_tables.sql, database/scripts/140_create_references.sql
task:  8697ep5gn
[[Testy dev] EPIC - API v6 - Comments API.pdf](https://github.com/user-attachments/files/18387476/Testy.dev.EPIC.-.API.v6.-.Comments.API.pdf)
Link to tests and documentation: https://pejot.sharepoint.com/:w:/s/MeowHub/EecMoX00WaNOhI_js4OAi1ABVLnzbRJ44TP9B4Er7GA19Q?e=bqInZn
=> feature: add comments API

backend/src/main/java/meowhub/backend/profiles/dtos/ProfileDto.java, backend/src/main/java/meowhub/backend/profiles/repositories/ProfileRepository.java
=> feature: add information of date of creation to profileDto

backend/src/main/java/meowhub/backend/posts/controllers/PostController.java, backend/src/main/java/meowhub/backend/posts/repositories/PostRepository.java, backend/src/main/java/meowhub/backend/posts/services/PostService.java, backend/src/main/java/meowhub/backend/posts/services/impl/PostServiceImpl.java, backend/src/main/java/meowhub/backend/profiles/dtos/ProfileDto.java, backend/src/main/java/meowhub/backend/profiles/repositories/ProfilePictureRepository.java, backend/src/main/java/meowhub/backend/profiles/repositories/ProfileRepository.java, backend/src/main/java/meowhub/backend/profiles/services/impl/ProfileServiceImpl.java, backend/src/test/java/meowhub/backend/posts/PostControllerIntegrationTest.java
Added:
1. an endpoint to get a post by id
2. gender value to ProfileDto
3. fix error that happened during adding new ProfilePicture
=> Cu 8697gdchv additional tasks kinga traczyk

frontend/src/Features/Profile/components/ProfileTop/CardProfileTop.tsx, frontend/src/Features/Root/Root.tsx, frontend/src/Features/SharedPost/SharedPost.tsx, frontend/src/Features/SharedPost/index.tsx, frontend/src/Features/shared/components/Cards/Post/DetailedPost.tsx, frontend/src/Features/shared/components/Cards/Post/Post.tsx, frontend/src/Features/shared/components/Cards/Post/components/Comment/Comment.tsx, frontend/src/Features/shared/components/Cards/Post/components/Comment/index.tsx, frontend/src/Features/shared/components/Cards/Post/components/CommentsSection/CommentsSection.tsx, frontend/src/Features/shared/components/Cards/Post/components/CommentsSection/index.tsx, frontend/src/Features/shared/components/Cards/Post/components/ReactionButton/ReactionButton.tsx, frontend/src/Features/shared/components/Cards/Post/components/ReactionButton/index.tsx, frontend/src/Features/shared/components/Cards/Post/components/ShareButton/ShareButton.tsx, frontend/src/Features/shared/components/Cards/Post/components/ShareButton/index.tsx, frontend/src/Features/shared/components/Cards/Post/index.tsx, frontend/src/Features/shared/components/Cards/Post/types/CommentDTO.tsx, frontend/src/Features/shared/components/Cards/Post/types/index.tsx, frontend/src/Features/shared/components/InfiniteScroll/InfiniteScroll.tsx, frontend/src/Features/shared/components/TruncatedText/TruncatedText.tsx, frontend/src/Features/shared/components/TruncatedText/index.tsx, frontend/src/Features/shared/utils/RenderPhotos.tsx, frontend/src/Features/shared/utils/index.tsx, frontend/src/Translations/en/components/post.json, frontend/src/Translations/en/components/truncatedText.json, frontend/src/Translations/pl/components/post.json, frontend/src/Translations/pl/components/truncatedText.json, frontend/src/Utils/i18nInitializer.tsx, frontend/src/main.tsx
- Add new translations
- Implement comments with all functionalities,
- Create base functionality for reactions
- Create share button
Refs: CU-8697jhjf
=> feature: Enhance post page.

backend/src/main/java/meowhub/backend/matching/constants/LikeTypes.java, backend/src/main/java/meowhub/backend/matching/controllers/MatchingProfileController.java, backend/src/main/java/meowhub/backend/matching/controllers/MatchingRelationsController.java, backend/src/main/java/meowhub/backend/matching/dtos/BasicMatchingProfileInfoDto.java, backend/src/main/java/meowhub/backend/matching/dtos/MatchingProfileDto.java, backend/src/main/java/meowhub/backend/matching/models/MatchingProfilePicture.java, backend/src/main/java/meowhub/backend/matching/repositories/LikeTypeRepository.java, backend/src/main/java/meowhub/backend/matching/repositories/LikedRepository.java, backend/src/main/java/meowhub/backend/matching/repositories/MatchingProfilePictureRepository.java, backend/src/main/java/meowhub/backend/matching/services/MatchingProfileService.java, backend/src/main/java/meowhub/backend/matching/services/MatchingRelationService.java, backend/src/main/java/meowhub/backend/matching/services/impl/MatchingProfileServiceImpl.java, backend/src/main/java/meowhub/backend/matching/services/impl/MatchingRelationServiceImpl.java, backend/src/main/java/meowhub/backend/posts/repositories/PostPictureRepository.java, backend/src/main/java/meowhub/backend/shared/constants/AlertConstants.java, backend/src/main/java/meowhub/backend/shared/dtos/PictureDto.java, database/scripts/120_create_tables.sql, database/scripts/160_create_indexes.sql, database/scripts/500_insert_dictionaries.sql
task:  8697evcyt
Developer tests: 
[[Testy dev] EPIC - API v8 - Matching Relations API.pdf](https://github.com/user-attachments/files/18524183/Testy.dev.EPIC.-.API.v8.-.Matching.Relations.API.pdf)
=> feature: matching relations crud

backend/src/main/java/meowhub/backend/user_relations/controllers/UserRelationController.java, backend/src/main/java/meowhub/backend/user_relations/repositories/UserRelationRepository.java, backend/src/main/java/meowhub/backend/user_relations/services/UserRelationService.java, backend/src/main/java/meowhub/backend/user_relations/services/impl/UserRelationServiceImpl.java, backend/src/test/java/meowhub/backend/user_relations/UserRelationControllerIntegrationTest.java
task:  8697njkem
[[Testy dev] add 'delete sent invitation' endpoint.pdf](https://github.com/user-attachments/files/18538890/Testy.dev.add.delete.sent.invitation.endpoint.pdf)
=> feature: add an endpoint to delete a sent invitation

frontend/vite.config.ts
- Add support of dynamic paths in URI
Refs: CU-8697nvcqu
=> feature: Update vite.config.ts

render.yaml
- Add support of dynamic paths in URI
Refs: CU-8697nt46x
=> feature: Add render.yaml

backend/src/main/java/meowhub/backend/users/controllers/SettingsController.java, backend/src/main/java/meowhub/backend/users/services/SettingsService.java, backend/src/main/java/meowhub/backend/users/services/impl/SettingsServiceImpl.java
=> feature: add an endpoint to change privacy settings

backend/src/main/java/meowhub/backend/security/SecurityConfig.java, backend/src/main/java/meowhub/backend/users/controllers/SettingsController.java, backend/src/main/java/meowhub/backend/users/facades/impl/UserAuthServiceFacadeImpl.java, backend/src/main/java/meowhub/backend/users/services/PasswordValidator.java, backend/src/main/java/meowhub/backend/users/services/SettingsService.java, backend/src/main/java/meowhub/backend/users/services/impl/SettingsServiceImpl.java
=> feature: Change password from settings window

backend/src/main/java/meowhub/backend/matching/models/Liked.java, backend/src/main/java/meowhub/backend/matching/models/MatchingProfile.java, backend/src/main/java/meowhub/backend/matching/models/MatchingProfilePicture.java, backend/src/main/java/meowhub/backend/posts/models/Comment.java, backend/src/main/java/meowhub/backend/posts/models/Post.java, backend/src/main/java/meowhub/backend/posts/models/PostPicture.java, backend/src/main/java/meowhub/backend/profiles/models/Profile.java, backend/src/main/java/meowhub/backend/profiles/models/ProfilePicture.java, backend/src/main/java/meowhub/backend/user_relations/models/UserRelation.java, backend/src/main/java/meowhub/backend/users/controllers/SettingsController.java, backend/src/main/java/meowhub/backend/users/services/SettingsService.java, backend/src/main/java/meowhub/backend/users/services/impl/SettingsServiceImpl.java, database/scripts/140_create_references.sql, database/scripts/160_create_indexes.sql
=> feature: delete MeowHub account + fix of deleting matching profile 

README.md, backend/pom.xml, backend/src/main/java/meowhub/backend/ext/oci/MockOCIDeleteService.java, backend/src/main/java/meowhub/backend/ext/oci/MockOCIUploadService.java, backend/src/main/java/meowhub/backend/security/controllers/AuthController.java, backend/src/main/java/meowhub/backend/security/jwt/JwtUtils.java, backend/src/main/java/meowhub/backend/security/services/AuthService.java, backend/src/main/java/meowhub/backend/security/services/impl/AuthServiceImpl.java, backend/src/main/java/meowhub/backend/shared/constants/AlertConstants.java, backend/src/main/java/meowhub/backend/shared/handlers/GlobalExceptionHandler.java, backend/src/main/java/meowhub/backend/shared/mail/MailService.java, backend/src/main/java/meowhub/backend/shared/mail/MockMailService.java, backend/src/main/java/meowhub/backend/shared/utils/AlertUtils.java, backend/src/main/java/meowhub/backend/users/facades/UserAuthServiceFacade.java, backend/src/main/java/meowhub/backend/users/facades/impl/UserAuthServiceFacadeImpl.java, backend/src/main/resources/application-mock-mail.properties, backend/src/main/resources/application.properties, backend/src/test/resources/application-test.properties
task:  8697nwkwy
Added reset password by using a link sent by email.
Sending a request:
Mail:
Using the link:
Additionally added a mock-mail profile which allows developers to test the functionality without sending emails -> they are logged onto console:
=> feature: Add mailService for password retrieval

frontend/src/Features/Profile/Profile.tsx, frontend/src/Features/Profile/components/ProfileTop/CardProfileTop.tsx, frontend/src/Features/Profile/consts/Profile.tsx, frontend/src/Features/shared/components/InvitationStatus/InvitationStatus.tsx, frontend/src/Features/shared/services/relationStatus.ts, frontend/src/Features/shared/types/User.tsx
- Adapt components to recognize levels of privacy
- Repair relation status component
Refs: CU-8697pgzpy
=> bug: Repair Profile displaying

frontend/src/Features/Login/Login.tsx, frontend/src/Features/Recovery/Recovery.tsx, frontend/src/Translations/en/recovery.json, frontend/src/Translations/pl/recovery.json
- Correct bug with the wrong method of navigate on Login.tsx
- Connect password recovery with backend
Refs: CU-8697ph09h
=> feature: Update recovery

backend/src/main/java/meowhub/backend/matching/controllers/MatchingProfileController.java, backend/src/main/java/meowhub/backend/matching/dtos/CreateMatchingProfileRequestDto.java, backend/src/main/java/meowhub/backend/matching/services/MatchingProfileService.java, backend/src/main/java/meowhub/backend/matching/services/impl/MatchingProfileServiceImpl.java
=> feature: Create a matching profile from scratch

README.md, backend/src/main/java/meowhub/backend/matching/dtos/MatchingProfileDto.java, backend/src/main/java/meowhub/backend/matching/services/MatchingProfileService.java, backend/src/main/java/meowhub/backend/matching/services/impl/MatchingProfileServiceImpl.java, backend/src/main/java/meowhub/backend/posts/repositories/PostPictureRepository.java, backend/src/main/java/meowhub/backend/posts/services/impl/PostServiceImpl.java, backend/src/main/java/meowhub/backend/shared/dtos/PictureDto.java, backend/src/main/java/meowhub/backend/users/controllers/SettingsController.java, backend/src/main/java/meowhub/backend/users/dtos/PrivacySettingsDto.java, backend/src/main/java/meowhub/backend/users/repositories/UserRepository.java, backend/src/main/java/meowhub/backend/users/services/SettingsService.java, backend/src/main/java/meowhub/backend/users/services/impl/SettingsServiceImpl.java
task:  8697q5zpm
Quick fixes:
- README
- delete from PictureDto not needed value isCurrentProfilePicture
- add max 5 pictures per post
- add privacy settings get endpoint
- repair getPostById (it didn't show pictures even though there were pictures)
=> bugfix: quick fixes

backend/src/main/java/meowhub/backend/user_relations/controllers/UserRelationController.java, backend/src/main/java/meowhub/backend/user_relations/repositories/UserRelationRepository.java, backend/src/main/java/meowhub/backend/user_relations/services/UserRelationQueryService.java, backend/src/main/java/meowhub/backend/user_relations/services/impl/UserRelationQueryServiceImpl.java, backend/src/test/java/meowhub/backend/user_relations/UserRelationQueryServiceImplTest.java
=> chore: CR - viewing own friends

frontend/src/Features/shared/services/api.ts, frontend/vite.config.ts
- Set up api.ts and vite.config.ts
Refs: CU-8697qytbu
=> feature: Adapt settings

frontend/src/Features/Friends/Friends.tsx, frontend/src/Features/shared/services/relationStatus.ts
- Update all occurences of /api/relations/friends
Refs: CU-8697qz44p
=> feature: Viewing own friends

backend/src/main/java/meowhub/backend/matching/controllers/MatchingProfileController.java, backend/src/main/java/meowhub/backend/matching/dtos/MatchingProfilePreferencesDto.java, backend/src/main/java/meowhub/backend/matching/models/MatchingProfile.java, backend/src/main/java/meowhub/backend/matching/services/MatchingProfileQueryService.java, backend/src/main/java/meowhub/backend/matching/services/MatchingProfileService.java, backend/src/main/java/meowhub/backend/matching/services/impl/MatchingProfileQueryServiceImpl.java, backend/src/main/java/meowhub/backend/matching/services/impl/MatchingProfileServiceImpl.java, backend/src/main/java/meowhub/backend/posts/repositories/PostRepository.java, backend/src/main/java/meowhub/backend/shared/constants/AlertConstants.java, backend/src/main/java/meowhub/backend/shared/handlers/GlobalExceptionHandler.java, backend/src/main/java/meowhub/backend/shared/utils/AlertUtils.java, database/scripts/120_create_tables.sql, database/scripts/140_create_references.sql
task:  8697qpb21
for now i added simple request values validations and any errors thrown by them are handled and returned in 400 Bad request - please note, that this error is handled in this way mostly for development - filters provided by frontend should not exceed specified values.
=> chore: add filters for matching + small fixes

backend/src/main/java/meowhub/backend/security/SecurityConfig.java, backend/src/main/resources/application-dev.properties, backend/src/main/resources/application.properties, backend/src/test/resources/application-test.properties
=> chore: add CORS handling

frontend/src/Features/shared/services/api.ts
- Update api.ts
Refs: CU-8697qz44p
=> chore: Update XSRF address on MASTER

frontend/src/Features/shared/services/api.ts
- Update api.ts
Refs: CU-8697qz44p
=> chore: Update api config MASTER

frontend/src/Features/Friends/components/FriendDetailed/FriendDetailed.tsx, frontend/src/Features/Profile/Profile.tsx, frontend/src/Features/Profile/components/ProfileFriends/ProfileFriends.tsx, frontend/src/Features/Root/Root.tsx, frontend/src/Features/Search/Search.tsx, frontend/src/Features/shared/components/Cards/Post/DetailedPost.tsx, frontend/src/Features/shared/components/Cards/Post/Post.tsx, frontend/src/Features/shared/components/InvitationStatus/InvitationStatus.tsx, frontend/src/Providers/CustomMantineProvider.tsx
- Correct translate
- Correct Invitation bug
- Correct comments section
- Correct profiles
Refs: CU-8697t4030
=> refactor: Correct code

backend/src/main/java/meowhub/backend/matching/dtos/MatchingProfilePreferencesDto.java
=> bugfix: get preferences throwing nullpointer

frontend/src/Features/Matching/components/Aside/Aside.tsx, frontend/src/Features/Matching/components/Filters/MatchFilters.tsx, frontend/src/Features/Matching/components/Main/Main.tsx, frontend/src/Features/Matching/components/Profile/consts/Filters.tsx, frontend/src/Features/Matching/services/matchingStore.ts, frontend/src/Features/Matching/types/MatchingProfile.tsx, frontend/src/Features/Matching/types/index.tsx, frontend/src/Translations/en/matching.json, frontend/src/Translations/pl/matching.json
Add api connection to filters
Refs: CU-8697uw0q7
=> feature: Adapt filters

backend/src/main/java/meowhub/backend/security/SecurityConfig.java
=> fix: Websocet
